apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-es-pv-master
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-data/es/master"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-es-pv-data-0
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-data/es/data0"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-es-pv-data-1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-data/es/data1"

